Added Basic Nav with Basic Styling
iO-Academy/23-sept-sarcasticfringeheads-bookswap-fe pull request #4
Opened 2023-10-30 14:24 UTC by shellycs50

2023-10-30 15:40 UTC, Geoff10 requested changes
Good work, I left a few small comments.

2023-10-30 15:40 UTC, Geoff10 commented on src/App.jsx
> +import Error from './components/Error/Error'
Must: The casing on the filenames here is inconsistent, please could the Home import be updated to match the others?

2023-10-30 15:40 UTC, Geoff10 commented on src/App.jsx
> +   </BrowserRouter>
Should: The indentation needs to be fixed here to improve the code readability.
Also worth considering removing some of the extr new lines for the same reason.

2023-10-30 15:40 UTC, Geoff10 commented on src/components/Booklisting/Booklisting.css
> +    /* border: solid 1px; */
Should: remove this commented out code if it is not being used.

2023-10-30 15:40 UTC, Geoff10 commented on src/components/Booklisting/Booklisting.jsx
> +        </div>
Should: fix the indentation here to imporove code readability.

2023-10-30 15:40 UTC, Geoff10 commented on src/components/Error/Error.jsx
> +        <>
Should: the fragment is not needed as there is only a single root element.

2023-10-30 15:40 UTC, Geoff10 commented on src/App.jsx
>  function App() {
Should: Put a newline after the imports.

2023-10-30 15:40 UTC, Geoff10 commented on src/components/Booklisting/Booklisting.jsx
> +// booklisting will take props to display JSON data from Home
Should: Put a newline after the imports.

2023-10-30 15:40 UTC, Geoff10 commented on src/components/Home/Home.css
> +
Should: This line is not needed.

2023-10-30 15:40 UTC, Geoff10 commented on src/components/Home/Home.jsx
> +            <BookListing title={book.title} author={book.author} image={book.image} genre={book.genre.name} />
Must: The `key` attribute is missing here and causing a console error.

2023-10-30 15:40 UTC, Geoff10 commented on src/components/Home/Home.jsx
> +
Should: remove the extra newline here.

2023-10-30 15:40 UTC, Geoff10 commented on src/components/Home/Home.jsx
> +        <>
Should: The fragment is not needed here as the `div` is the only root element.

2023-10-30 15:40 UTC, Geoff10 commented on src/components/Home/Home.jsx
> +            <BookListing title={book.title} author={book.author} image={book.image} genre={book.genre.name} />
Should: indentation for readability.

2023-10-30 15:40 UTC, Geoff10 commented on src/components/Nav/Nav.jsx
> +        <>
Should: fragment is not needed here as there is only one root element.

2023-10-30 15:40 UTC, Geoff10 commented on src/components/Nav/Nav.css
> +nav {
The content is visible behing the navbar making the items in the navbar difficult to read.
![image](https://github.com/iO-Academy/23-sept-sarcasticfringeheads-bookswap-fe/assets/9077806/a217f5cc-5ced-4ce8-af4a-4e60fd965b10)

2023-10-30 15:40 UTC, Geoff10 commented on src/components/Nav/Nav.css
> +nav {
On smaller screens, the navbar is quite large and the "Book swap" text is cut off.
![image](https://github.com/iO-Academy/23-sept-sarcasticfringeheads-bookswap-fe/assets/9077806/96320303-2017-46a2-a279-83bb100ac1c6)

2023-10-31 10:15 UTC, shellycs50 commented
Completed all requested changes in the Story 2 branch.

2023-11-01 15:00 UTC, merged